# Generated by Django 2.2.1 on 2019-05-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
