# Generated by Django 2.2.1 on 2019-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_won',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
